import numpy as np
import matplotlib.pyplot as plt

## ------ EAE 130A, preliminary design sizing ------ ##
## ------ Team 7 Avion: Mostafa Hashem, Charlie Stone, Jose Hernandez Negrete, ------ ##
## ------ Valeria Cecena, Quinn Kennerly, Lena Pattamadilok ------ ##

#region inputs
g = 32.174 #ft/s^2, gravitational acceleration
tar_togw = 50000 #lbf, target gross take off weight
S_i = 600 #ft^2, initial wing area assumption including strakes (LERX)
S_ialt = 400 #ft^2, initial wing area assumption not including strakes (LERX)
C_D0 = 0.01755 #initial zero-lift drag estimation, from OpenVSP, see:
#(https://github.com/charliesstone/EAE130SP_AVION7/blob/main/Assignments/A2/Concepts/concept_1_COYOTE.vsp3)
e = 0.8 #oswald efficiency factor for fighters, from raymond textbook
AR = 3.5 #aspect ratio, from OpenVSP main wing, not including strakes (LERX)
n_tar = 7.0 #load factor, minimum targeted
n_idl = 8.0 #load factor, ideal targeted
wingload = np.linspace(0.1, 200, 500)
thrustload = np.linspace(0.1, 2.5, 500)
VWOD = 51 #ft/s (30 kts) "Wind Over Deck" airspeed, or wind speed + carrier cruise velocity
VCAT = 200 #ft/s (120 kts) airspeed generated by forward throw of CATapult 
k = 1/(np.pi * e * AR) #drag polar constant, see 07-PreliminarySizing_Part3.pdf pg15 in canvas files
#endregion

#region stall
Vstall_L = 195 #ft/s (115 KIAS), stall speed for landing (based on F/A-18E/F)
Vstall_C = 210 #ft/s (130 KIAS), stall speed for cruise (based on F/A-18E/F)
Vstall_T = 205 #ft/s (120 KIAS), stall speed for takeoff (based on F/A-18E/F)
rho_30k = 8.91E-4 #slugs/ft^3, atmospheric density at 30k ft
rho_20k = 12.66E-4 #slugs/ft^3, atmospheric density at 20k ft
rho_SL = 23.77E-4 #slugs/ft^3, atmospheric density at sea level
CLmax_L = 2.0 #CLmax at landing
CLmax_C = 1.5 #CLmax at cruise
CLmax_T = 1.7 #CLmax at takeoff

def stall(V, CL, rho):
    FoS = 1.25 #stall factor of safety
    WS = (rho * CL * V**2)/2
    return WS
stallWS_L = stall(Vstall_L, CLmax_L, rho_SL) #wing loading constraint for stall on landing
#stallWS_C = stall(Vstall_C, CLmax_C, rho_30k) #wing loading constraint for stall on cruise (&note: ask if this must be incl.)
stallWS_T = stall(Vstall_T, CLmax_T, rho_SL) #wing loading constraint for stall on takeoff
#endregion

#region takeoff
def takeoff(rho, Vwod, Vcat, CLMT):
    WS = (0.5 * rho * (Vwod + Vcat)**2 * CLMT)/1.21 #equation from slides 06-PreliminarySizing_Part2 pg27
    return WS
takeoffWS = takeoff(rho_SL, VWOD, VCAT, CLmax_T) #wing loading constraint for clearing carrier runway on takeoff

#endregion

#region climb
#assume CLmax_climb = CLmax_T (takeoff)
def climb(k, Cd0, CLMCLB):
    ks = 3.4 #Vclimb ~ Vstall proportionality constant (using Vclimb 748 ft/s, MROC for Super Hornet, and Vstall_C)
    G = 0.14 #ft/ft (unitless) Climb Gradient, = sin(g) ~= g, where g = climb pitch angle
    tempoverinc = 1/(0.8) #loss of thrust due to 50F increase over standard temperature
    maxcont2max = 1/(0.94) #ratio of maximum continuous to maximum peak thrust
    TW_gen = (ks**2 * Cd0)/(CLMCLB) + k * (CLMCLB)/(ks**2) + G
    TW = tempoverinc * maxcont2max * TW_gen #other parameters not included, see 07-PreliminarySizing_Part3.pdf pg20
    return TW
climbTW = climb(k, C_D0, CLmax_T)
#endregion



#region cruise/dash
M_cruiseidl = 2.0
M_cruise_tar = 1.6
Wf_Wi_cruise = 0.7706 #Cruise/Takeoff weight fraction, from A2 sizing code
Tcr_Tto = 22/13 #Cruise/Takeoff thrust fraction, from the GE F414 engine deck (&note: refine value for A3)
def cruise(Cd0, k, WS, M, rho):
    a30k = 996 #996 ft/s is speed of sound at 30kft from NASA standard atmosphere tables
    Vcruise = M * a30k #Mach * speed of sound
    qcr = 1/2 * rho * Vcruise**2 #lbf/ft^2, dynamic pressure at cruise velocity
    WS_cruise = WS * Wf_Wi_cruise #wing loading at cruise, as opposed to takeoff
    TW = Wf_Wi_cruise/Tcr_Tto * ( (qcr * Cd0)/(WS_cruise) + k/qcr * (WS_cruise) ) #thrust loading at takeoff as a function of wing loading at cruise -> wing loading at takeoff
    return TW
cruiseTWMa2 = cruise(C_D0, k, wingload, M_cruiseidl, rho_30k)
cruiseTWMa1p6 = cruise(C_D0, k, wingload, M_cruise_tar, rho_30k)
#endregion

#region ceiling
ceilingTW = (Wf_Wi_cruise/Tcr_Tto) * 2 * np.sqrt(k * C_D0)
#endregion

#region maneuver
psi_dot_tar = 0.14 #rad/s (8 deg/s) minimum targeted sustained turn rate (from RFP)
psi_dot_idl = 0.17 #rad/s (10 deg/s) minimum ideal sustained turn rate (from RFP)
V_BTR = 640 #ft/s (380 KIAS) best turn speed for F-18 Hornet (via DCS TacView)
def turnrateload(psi, g, V):
    n_BTR = np.sqrt(((psi * V)/(g))**2 + 1) #load factor corresponding to the best turn speed
    return n_BTR
n_BTR_tar = turnrateload(psi_dot_tar, g, V_BTR)
n_BTR_idl = turnrateload(psi_dot_idl, g, V_BTR)

def maneuver(Cd0, k, n, rho, V, wingload):
    q = 1/2 * rho * V**2 #dynamic pressure at 20kft using best turn speed
    TW = (q * Cd0)/wingload + k * (n**2)/(q) * wingload
    return TW

maneuverTW_BTR_tar = maneuver(C_D0, k, n_BTR_tar, rho_20k, V_BTR, wingload)
maneuverTW_MAX_tar = maneuver(C_D0, k, n_tar, rho_20k, V_BTR, wingload)
maneuverTW_BTR_idl = maneuver(C_D0, k, n_BTR_idl, rho_20k, V_BTR, wingload)
maneuverTW_MAX_idl = maneuver(C_D0, k, n_idl, rho_20k, V_BTR, wingload)

#region plotting

plt.figure(figsize=(10, 7))

# ---- Vertical constraints (W/S limits) ----
plt.axvline(stallWS_L, color='red', linestyle='--', label='Stall (Landing)')
plt.axvline(stallWS_T, color='orange', linestyle='--', label='Stall (Takeoff)')
# plt.axvline(stallWS_C, color='brown', linestyle='--', label='Stall (Cruise)')
plt.axvline(takeoffWS, color='purple', linestyle='--', label='Carrier Takeoff')

# ---- Horizontal constraints (T/W limits) ----
plt.axhline(climbTW, color='green', linestyle='--', label='Climb')
plt.axhline(ceilingTW, color='darkgreen', linestyle='--', label='Ceiling')

# ---- Curved constraints ----
plt.plot(wingload, cruiseTWMa2, label='Cruise M2.0', linewidth=2)
plt.plot(wingload, cruiseTWMa1p6, label='Cruise M1.6', linewidth=2)

plt.plot(wingload, maneuverTW_BTR_tar, label='Maneuver BTR (Target)', linestyle='-.')
plt.plot(wingload, maneuverTW_MAX_tar, label='Maneuver Max n (Target)', linestyle=':')

plt.plot(wingload, maneuverTW_BTR_idl, label='Maneuver BTR (Ideal)', linestyle='-.')
plt.plot(wingload, maneuverTW_MAX_idl, label='Maneuver Max n (Ideal)', linestyle=':')

# ---- Formatting ----
plt.xlim(0, 200)
plt.ylim(0, 2.5)
plt.xlabel('Wing Loading W/S (lbf/ft²)')
plt.ylabel('Thrust-to-Weight Ratio T/W')
plt.title('Aircraft Constraint Diagram')
plt.grid(True)
plt.legend(loc='upper left', fontsize=9)

plt.show()

#endregion
  







