import numpy as np
import matplotlib.pyplot as plt

## ------ EAE 130A, preliminary design sizing ------ ##
## ------ Team 7 Avion: Mostafa Hashem, Charlie Stone, Jose Hernandez Negrete, ------ ##
## ------ Valeria Cecena, Quinn Kennerly, Lena Pattamadilok ------ ##

#region inputs
g = 32.174 #ft/s^2, gravitational acceleration
tar_togw = 50000 #lbf, target gross take off weight
S_LERX = 70 #ft^2, wing area of strakes from OpenVSP
Sref = 375 #ft^2, initial wing area assumption not including strakes (LERX)
Sreftot = Sref + S_LERX #ft^2, initial wing area assumption including strakes (LERX)
C_D0 = 0.01395 #initial zero-lift drag estimation, from OpenVSP
e_clean   = 0.85
e_takeoff = 0.75
e_landing = 0.7
# ^^^^^^ all from raymer textbook
nztar = 7 #target maximum structual load factor
nzidl = 8 #ideal maximum structual load factor
AR = 3.5 #aspect ratio, from OpenVSP main wing, not including strakes (LERX)
wingload = np.linspace(1, 200, 500)
thrustload = np.linspace(1, 2.5, 500)
VWOD = 50.63 #ft/s (15 kts) "Wind Over Deck" airspeed, or wind speed + carrier cruise velocity
VCAT = 200 #ft/s (120 kts) airspeed generated by forward throw of CATapult 
k_clean   = 1 / (np.pi * e_clean * AR)
k_takeoff = 1 / (np.pi * e_takeoff * AR)
k_landing = 1 / (np.pi * e_landing * AR) #drag polar constant, see 07-PreliminarySizing_Part3.pdf pg15 in canvas files

# ADDED: maneuver-weight fraction to reduce sustained-turn / structural-load TW to realistic combat values
Wf_Wi_manuv = 0.7706
#endregion

#region stall
Vstall_L = 195 #ft/s (115 KIAS), stall speed for landing (based on F/A-18E/F)
Vstall_C = 220 #ft/s (130 KIAS), stall speed for cruise (based on F/A-18E/F)
Vstall_T = 205 #ft/s (120 KIAS), stall speed for takeoff (based on F/A-18E/F)
rho_30k = 8.91E-4 #slugs/ft^3, atmospheric density at 30k ft
rho_SL = 23.77E-4 #slugs/ft^3, atmospheric density at sea level

# ADJUSTED: restored higher validated CLmax values so landing/takeoff/catapult WS limits shift left in T-S and appear more vertical
CLmax_L = 2.8
CLmax_C = 1.6
CLmax_T = 2.2

def stall(V, CL, rho):
    WS = (rho * CL * V**2) / 2
    return WS

stallWS_L = stall(Vstall_L, CLmax_L, rho_SL) #wing loading constraint for stall on landing
stallWS_C = stall(Vstall_C, CLmax_C, rho_30k) #wing loading constraint for stall on cruise
stallWS_T = stall(Vstall_T, CLmax_T, rho_SL) #wing loading constraint for stall on takeoff
#endregion

#region takeoff
def takeoff(rho, Vwod, Vcat, CLMT):
    WS = (0.5 * rho * (Vwod + Vcat)**2 * CLMT) / 1.21
    return WS

takeoffWS = takeoff(rho_SL, VWOD, VCAT, CLmax_T) #wing loading constraint for clearing carrier runway on takeoff

#endregion

#region climb
#assume CLmax_climb = CLmax_T (takeoff)
def climb(k, Cd0, CLMCLB):
    ks = 3.4 #Vclimb ~ Vstall proportionality constant (using Vclimb 748 ft/s, MROC for Super Hornet, and Vstall_C)
    G = 0.220 #ft/ft (unitless) Climb Gradient, = sin(g) ~= g, where g = climb pitch angle
    tempoverinc = 1/(0.8) #loss of thrust due to 50F increase over standard temperature
    maxcont2max = 1/(0.94) #ratio of maximum continuous to maximum peak thrust
    TW_gen = (ks**2 * Cd0)/(CLMCLB) + k * (CLMCLB)/(ks**2) + G
    TW = tempoverinc * maxcont2max * TW_gen #other parameters not included, see 07-PreliminarySizing_Part3.pdf pg20
    return TW

climbTW = climb(k_takeoff, C_D0, CLmax_T)
#endregion

#region ceiling
def ceiling():
    """
    Calculates the fixed TW required for the ceiling constraint
    """
    return 2 * np.sqrt(k_clean * C_D0)

ceilingTW = ceiling()

#endregion

#region cruise/dash
M_cruiseidl = 2.0
M_cruise_tar = 1.6

def dash(WS, M):
    Wf_Wi_cruise = 0.7706 #Cruise/Takeoff weight fraction, from A2 sizing code
    Tcr_Tto = 1 #Cruise/Takeoff thrust fraction, from the GE F414 engine deck (note: refine value for A3)
    Vcruise = M * 996 #996 ft/s is speed of sound at 30kft from NASA standard atmosphere tables
    qcr = 1/2 * rho_30k * Vcruise**2 #lbf/ft^2, dynamic pressure at cruise velocity
    WS_cruise = WS * Wf_Wi_cruise #wing loading at cruise, as opposed to takeoff 
    cruise_coef1 = Wf_Wi_cruise/Tcr_Tto * (qcr * C_D0)
    cruise_coef2 = Wf_Wi_cruise/Tcr_Tto * (k_clean/qcr)
    TW = cruise_coef1/WS_cruise + cruise_coef2 * WS_cruise
    return TW, cruise_coef1, cruise_coef2

TW_cruiseMa2, cruise_coef1_idl, cruise_coef2_idl = dash(wingload, M_cruiseidl)
TW_cruiseMa1p6, cruise_coef1_tar, cruise_coef2_tar = dash(wingload, M_cruise_tar)

#region maneuverability 
# assume sustained turn at 20kft 
rho_20k = 0.001267  # slugs/ft^3 
V_turn = 1000       # ft/s 

def maneuver_TW(WS, turnrate):
    # target and ideal turn-rate maneuver constraints
    stall_coef = 2/(rho_20k*CLmax_C)
    V_stall = np.sqrt(stall_coef * WS)
    V_manuv = 3 * V_stall
    n = np.sqrt((turnrate * V_manuv / g)**2 + 1)

    q_manuv = 0.5 * rho_20k * V_manuv**2
    WS_manuv = Wf_Wi_manuv * WS   # ADJUSTED: evaluate turn-rate maneuver at maneuver-weight fraction instead of TOGW
    manuv_coef1 = Wf_Wi_manuv * q_manuv * C_D0  # ADJUSTED: consistent with takeoff-referenced TW form
    manuv_coef2 = Wf_Wi_manuv * k_clean * n**2 / q_manuv  # ADJUSTED: consistent with takeoff-referenced TW form
    TW = manuv_coef1/WS_manuv + manuv_coef2 * WS_manuv
    return TW, manuv_coef1, manuv_coef2

turnrate8 = 8 * np.pi/180
turnrate10 = 10 * np.pi/180

def structloads_TW(WS, n):
    # target and ideal structural load constraints
    q_turn = 0.5 * rho_20k * V_turn**2
    WS_manuv = Wf_Wi_manuv * WS   # ADJUSTED: structural-load sustained turn should use maneuver weight, not takeoff weight
    loads_coef1 = Wf_Wi_manuv * q_turn * C_D0
    loads_coef2 = Wf_Wi_manuv * k_clean * n**2 / q_turn
    TW = loads_coef1/WS_manuv + loads_coef2 * WS_manuv
    return TW, loads_coef1, loads_coef2

TW_manuv8deg, manuv_coef1_8deg, manuv_coef2_8deg = maneuver_TW(wingload, turnrate8)
TW_manuv10deg, manuv_coef1_10deg, manuv_coef2_10deg = maneuver_TW(wingload, turnrate10)
TW_load7g, loads_coef1_7g, loads_coef2_7g = structloads_TW(wingload, nztar)
TW_load8g, loads_coef1_8g, loads_coef2_8g = structloads_TW(wingload, nzidl)
#endregion


#region constraint diagram plot
plt.figure(figsize=(16,9))

colors = plt.rcParams['axes.prop_cycle'].by_key()['color']
ci = 0
def nextc():
    global ci
    c = colors[ci % len(colors)]
    ci += 1
    return c

plt.plot(wingload, TW_cruiseMa1p6, linewidth=2, label="Dash: Mach 1.6 @ 30kft", color=nextc())
plt.plot(wingload, TW_cruiseMa2, linewidth=2, label="Dash: Mach 2.0 @ 30kft (ideal)", color=nextc())

plt.plot(wingload, TW_manuv8deg, linewidth=2, label="Sustained turn: 8 deg/s @ 20kft", color=nextc())
plt.plot(wingload, TW_manuv10deg, linewidth=2, label="Sustained turn: 10 deg/s @ 20kft", color=nextc())
plt.plot(wingload, TW_load7g, linewidth=2, label="Sustained Turn, n = 7g", color=nextc())
plt.plot(wingload, TW_load8g, linewidth=2, label="Sustained Turn, n = 8g", color=nextc())

plt.hlines(ceiling(), xmin=wingload.min(), xmax=wingload.max(),
           linewidth=2, label="Service ceiling (approx)", color=nextc())

plt.hlines(climbTW, xmin=wingload.min(), xmax=wingload.max(),
           linewidth=2, label="Climb constraint (approx)", color=nextc())

plt.axvline(stallWS_L, linewidth=2, label="Stall (landing) W/S limit", color=nextc())
plt.axvline(stallWS_T, linewidth=2, label="Stall (takeoff) W/S limit", color=nextc())
plt.axvline(takeoffWS, linewidth=2, label="Catapult takeoff W/S limit", color=nextc())

#plotting of aircraft of comparible role:

#takeoff ground weight in lbf
TOGW_aircrafts = {
    "YF-52 Coyote (AVION)": 36721.66,
    "F-35A (USA)": 49450,
    "F/A-18E/F (USA)": 47000,
    "J-35 (PRC)": 48943,
    "Euro. Typhoon (EU)": 35274,
    "Su-27 (RUS)": 67130
}

#wing areas of reference aircrafts, in ft^2:
S_aircrafts = {
    "YF-52 Coyote (AVION)": 400,
    "F-35A (USA)": 460,
    "F/A-18E/F (USA)": 500,
    "J-35 (PRC)": 660,
    "Euro. Typhoon (EU)": 551,
    "Su-27 (RUS)": 670
}

#wet thrusts of reference aircrafts, in ft^2:
T_aircrafts = {
    "YF-52 Coyote (AVION)": 33500,
    "F-35A (USA)": 43000,
    "F/A-18E/F (USA)": 22000*2,
    "J-35 (PRC)": 26000*2,
    "Euro. Typhoon (EU)": 20200*2,
    "Su-27 (RUS)": 27600*2
}

#solving for wing loading and thrust loading of reference aircraft:
WS_aircrafts = {}
TW_aircrafts = {}

for name in TOGW_aircrafts:
    WS_aircrafts[name] = TOGW_aircrafts[name]/S_aircrafts[name]
    TW_aircrafts[name] = T_aircrafts[name]/TOGW_aircrafts[name]
    if name == "YF-52 Coyote (AVION)":
        plt.scatter(WS_aircrafts[name], TW_aircrafts[name], label=name, marker="D", color="gold", zorder=2)
    else:
        plt.scatter(WS_aircrafts[name], TW_aircrafts[name], label=name, marker="^")


# shaded area
TW_union = np.maximum(TW_cruiseMa2, TW_load8g)

plt.fill_between(
    wingload,
    0,
    TW_union,
    color="gray",
    alpha=0.25,
    zorder=0,
    label="Unfeasible region"
)
plt.fill_between(
    wingload,
    TW_load8g,
    plt.ylim()[1],         # top of current y-axis
    where=(wingload >= stallWS_T),
    color="gray",
    alpha=0.25,
    zorder=0
)


plt.xlim(1, 200)
plt.ylim(0, 2.5)
plt.xlabel("Wing Loading W/S (lbf/ft²)")
plt.ylabel("Thrust Loading T/W (lbf/lbf)")
plt.title("Nondimensionalized Mission Constraint Diagram")
plt.legend(loc="upper right")
# plt.show()
#endregion