import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#region drag polar
AR = 4.5 
S_ref = 400 #ft^2, initial wing area assumption not including strakes (LERX)
S_wet_fuselage = 288 #ft^2 openvsp
c_f = 0.0026
C_D_0 = 0.01755 #from openvsp
print("Zero-lift drag coefficient C_D_0:", C_D_0)
# Adjust C_Lmax for each flight configuration
cL_clean = np.linspace(-0.9,0.9,100)
cL_takeoff = np.linspace(-2,2,100)
cL_landing = np.linspace(-2.6,2.6,100)

# Clean configuration
def calculate_induced_drag_coefficient(AR, e):
    return 1/(np.pi*AR*e)
e_clean = 0.825
coef_clean = calculate_induced_drag_coefficient(AR, e_clean)
print("Induced drag coefficient for clean configuration:", coef_clean)
clean = C_D_0 + coef_clean*cL_clean*cL_clean

# Takeoff configuration
e_takeoff = 0.775
delta_CD0_takeoff = 0.015  # additional drag due to takeoff flaps
coef_takeoff = calculate_induced_drag_coefficient(AR, e_takeoff)
print("Induced drag coefficient for takeoff configuration:", coef_takeoff)
takeoff = C_D_0 + delta_CD0_takeoff + coef_takeoff*cL_takeoff*cL_takeoff 

# Landing configuration
e_landing = 0.725
delta_CD0_landing = 0.065 # additional drag due to landing flaps and gear
coef_landing = calculate_induced_drag_coefficient(AR, e_landing)
print("Induced drag coefficient for landing configuration:", coef_landing)
landing_flaps = C_D_0 + delta_CD0_landing + coef_landing*cL_landing*cL_landing

# Additional drag due to landing gear only
e_gear = e_clean # Assuming landing gear does not affect the efficiency factor
delta_CD0_gear = 0.020 # additional drag due to landing gear
coef_gear = calculate_induced_drag_coefficient(AR, e_gear)
landing_gear = C_D_0 + delta_CD0_gear + coef_gear*cL_landing*cL_landing

plt.figure(figsize=(16,9))
plt.title('Drag Polars')
plt.xlabel("$C_D$")
plt.ylabel("$C_L$")
plt.plot(clean, cL_clean, label='Clean', linestyle='-', linewidth=2)
plt.plot(takeoff, cL_takeoff, label='w. Takeoff flaps', linestyle='-', linewidth=2)
plt.plot(landing_flaps, cL_landing, label='w. Landing flaps', linestyle='-', linewidth=2)
plt.plot(landing_gear, cL_landing, label='w. Landing gear', linestyle='-', linewidth=2)
plt.legend(loc='best')
plt.show()

#region takeoff cat
C_L_max_takeoff = 2.0
rho_SL = 23.77E-4 #slugs/ft^3, atmospheric density at sea level
VWOD = 51 #ft/s (30 kts) "Wind Over Deck" airspeed, or wind speed + carrier cruise velocity
VCAT = 200 #ft/s (120 kts) airspeed generated by forward throw of CATapult 

def calculate_takeoff_cat_coefficient(Vwod, Vcat, rho, C_L_max_takeoff):
    coeff = (0.5 * rho * (Vwod + Vcat)**2 * C_L_max_takeoff)/1.21
    return coeff
coef_takeoff_constraint = calculate_takeoff_cat_coefficient(VWOD, VCAT, rho_SL, C_L_max_takeoff)
print("Coefficient of takeoff field length:", coef_takeoff_constraint)

#region landing stall
C_L_max_landing = 2.0
Vstall_L = 195 #ft/s (115 KIAS), stall speed for cruise (based on F/A-18E/F)
Vstall_C = 220 #ft/s (130 KIAS), stall speed for landing (based on F/A-18E/F)
Vstall_T = 205 #ft/s (120 KIAS), stall speed for takeoff (based on F/A-18E/F)
k_takeoff = 1/(np.pi * e_takeoff * AR) #drag polar constant, see 07-PreliminarySizing_Part3.pdf pg15 in canvas files

def calculate_landing_stall_coefficient(rho, CL, V):
    coeff = (rho * CL * V**2)/2
    return coeff
coef_landing_constraint = calculate_landing_stall_coefficient(rho_SL, C_L_max_landing, Vstall_L)
print("Coefficient of landing field length:", coef_landing_constraint)

#region climb
def calculate_climb_constraint_coefficient(k, Cd0, CLMCLB,):
    ks = 3.4 #Vclimb ~ Vstall proportionality constant (using Vclimb 748 ft/s, MROC for Super Hornet, and Vstall_C)
    G = 0.220 #ft/ft (unitless) Climb Gradient, = sin(g) ~= g, where g = climb pitch angle
    tempoverinc = 1/(0.8) #loss of thrust due to 50F increase over standard temperature
    maxcont2max = 1/(0.94) #ratio of maximum continuous to maximum peak thrust
    TW_gen = (ks**2 * Cd0)/(CLMCLB) + k * (CLMCLB)/(ks**2) + G
    coeff = tempoverinc * maxcont2max * TW_gen #other parameters not included, see 07-PreliminarySizing_Part3.pdf pg20
    return coeff
coef_1_climb_constraint = calculate_climb_constraint_coefficient(k_takeoff, C_D_0, C_L_max_takeoff)
print("Coefficient of takeoff climb:", coef_1_climb_constraint)

#region cruise/dash
rho_30k = 8.91E-4 #slugs/ft^3, atmospheric density at 30k ft
M_cruiseidl = 2.0
Vcruise = M_cruiseidl * 996 #996 ft/s is speed of sound at 30kft from NASA standard atmosphere tables
C_D_0_cruise = C_D_0        # C_D_0 at cruise is the same as clean configuration
e_cruise = e_clean          # Assuming cruise configuration is similar to clean configuration

def calculate_cruise_constraint_coefficients(rho, V, C_D_0, AR, e):
    q = 0.5 * rho * V**2   
    coef_1 = q * C_D_0
    coef_2 = 1/(np.pi * AR * e * q)
    return coef_1, coef_2

coef_1_cruise_constraint, coef_2_cruise_constraint = calculate_cruise_constraint_coefficients(rho_30k, Vcruise, C_D_0_cruise, AR, e_cruise)
print("Coefficient of cruise constraint (C_D_0 term):", coef_1_cruise_constraint)
print("Coefficient of cruise constraint (induced drag term):", coef_2_cruise_constraint)

#region TW WS diag
WS = np.linspace(1,300,100)

TW_takeoff = coef_takeoff_constraint*WS
TW_landing = coef_landing_constraint*np.ones(100)
TW_climb = coef_1_climb_constraint*np.ones(100)
TW_cruise = coef_1_cruise_constraint/WS + coef_2_cruise_constraint*WS

WS_777 = 160
TW_777 = 0.29

plt.figure(figsize=(16,9))
plt.title('T/W - W/S')
plt.xlabel("W/S $(lb/ft^2)$")
plt.ylabel("T/W")
plt.plot(WS, TW_takeoff, label='Takeoff field length', linestyle='-', linewidth=2)
plt.plot(TW_landing, np.linspace(0,1,100), label='Landing field length', linestyle='-', linewidth=2)
plt.plot(WS, TW_climb, label='Takeoff climb', linestyle='-', linewidth=2)
plt.plot(WS, TW_cruise, label='Cruise', linestyle='-', linewidth=2)
plt.plot(WS_777, TW_777, label='777', marker="o")
plt.ylim(0, 0.5)
plt.legend(loc='best')
plt.show()

#region weight def
num_pilot = 1
num_crew = 0
num_crew = num_pilot + num_crew

avg_wt_person = 200  #lbs


def kgs_to_lbs(weight_kg):
    return weight_kg * 2.20462

W_crew = num_crew * (avg_wt_person) # lbs

W_avionics = 2500.0  # [lb]
W_AIM9X  = 190   # [lb] 
W_MK83_JDAM = 1050  # [lb] 
W_payload = W_avionics + 4*W_MK83_JDAM + 2*W_AIM9X #Strike mission is used from 
# https://github.com/charliesstone/EAE130SP_AVION7/tree/main/Assignments/A2/Weight%26Cost/A2_weight_est_concept_2.py
#as it is more demanding than the air-to-air

#region engine weight
def calculate_engine_weight(T_0):
    """Calculate the single engine weight based on the given thrust using empirical relationships.
    Args:
        T_0 (float): Thrust in pounds-force (lbf).
    Returns:
        float: Estimated engine weight in pounds (lb).
    """
    W_eng_dry = 0.521 * T_0**0.9
    W_eng_oil = 0.082 * T_0**0.65
    W_eng_rev = 0.034 * T_0
    W_eng_control = 0.26 * T_0**0.5
    W_eng_start = 9.33 * (W_eng_dry/1000) ** 1.078
    W_eng = W_eng_dry + W_eng_oil + W_eng_rev + W_eng_control + W_eng_start
    return W_eng

# # For Test the function with a sample thrust value: GE90 has max thrust of around 85000 lbf and the weight is around 17400 lb.
# T_0 = 85000
# Engine_weight = calculate_engine_weight(T_0)
# print("Engine weight:", Engine_weight, "lb")

#region empty weight   
def calculate_empty_weight(S_wing, S_ht, S_vt, S_wet_fuselage, TOGW, T_0 , num_engines):
    W_wing = S_wing * 9
    W_ht = S_ht * 4
    W_vt = S_vt * 5.3
    W_fuselage = S_wet_fuselage * 4.8
    W_landing_gear = 0.045 * TOGW
    Engine_weight = calculate_engine_weight(T_0)
    W_engines = Engine_weight * num_engines * 1.3
    W_all_else = 0.17 * TOGW
    W_empty = W_wing + W_ht + W_vt + W_fuselage + W_landing_gear + W_engines + W_all_else
    return W_empty

# # For Test the function with sample values: for boeing 777-200 er, it is around 297300 lb
# S_wing = 4605
# S_ht = 1097
# S_vt = 709.9
# S_wet_fuselage = 11354
# TOGW = 580000  # Example value for Takeoff Gross Weight
# T_0 = 95000  # Example value for thrust per engine
# num_engines = 2  # Example number of engines
# estimated_empty_weight = calculate_empty_weight(S_wing, S_ht, S_vt, S_wet_fuselage, TOGW, T_0 , num_engines)
# print("Estimated empty weight:", estimated_empty_weight, "lb")

#region weight fraction
def calculate_weight_fraction(L_D_max, R, E, c, V):
    """This function calculates the weight fractions for cruise and loiter/descent phases based on the Breguet range and endurance equations, and also other terms.
    Args:
        L_D_max (float): Maximum lift-to-drag ratio of the aircraft.
        R (float): Range in nautical miles.
        E (float): Endurance in hours.
        c (float): Specific fuel consumption in lb/(lbf hr).
        V (float): Velocity in knots."""
    
    L_D = 0.94 * L_D_max

    W3_W2 = np.exp((-R*c) / (V*L_D))  # cruise
    # print("Cruise Fuel Fraction (W3/W2): " + str(round(W3_W2, 3)))

    W4_W3 = np.exp((-E*c) / (L_D))    # loiter/descent
    # print("Loiter Fuel Fraction (W4/W3): " + str(round(W4_W3, 3)))

    W1_W0 = 0.990   # engine start & takeoff
    W2_W1 = 0.980   # climb
    W5_W4 = 0.995   # landing
    #^^^^^ these have been changed from jupyter notebook values to values consistent with 
    # https://github.com/charliesstone/EAE130SP_AVION7/tree/main/Assignments/A2/Weight%26Cost/A2_weight_est_concept_2.py

    W5_W0 = W5_W4 * W4_W3 * W3_W2 * W2_W1 * W1_W0
    # print("Final Fuel Fraction (W5/W0): " + str(round(W5_W0, 3)))

    Wf_W0 = (1 - W5_W0) * 1.06    # compute fuel fraction
    # print("Total Fuel Fraction Wf/W0: {:.3f}".format(Wf_W0))

    return Wf_W0

#region inner loop def
def inner_loop_weight(
    TOGW_guess,
    S_wing, S_ht, S_vt, S_wet_fuselage,
    num_engines, w_crew, w_payload, T_0,
    err=1e-6,
    max_iter=200
):
    W0_history = []
    delta = np.inf
    it = 0

    while delta > err and it < max_iter:
        # 1) fuel fraction (could be constant or updated)
        Wf_W0 = calculate_weight_fraction(L_D_max, R, E, c, V)
        W_fuel = Wf_W0 * TOGW_guess

        # 2) empty weight based on current TOGW guess + geometry + thrust
        W_empty = calculate_empty_weight(
            S_wing, S_ht, S_vt, S_wet_fuselage,
            TOGW_guess, T_0, num_engines
        )

        # 3) new gross weight
        W0_new = W_empty + w_crew + w_payload + W_fuel
        W0_history.append(W0_new)

        # 4) convergence check
        delta = abs(W0_new - TOGW_guess) / max(abs(W0_new), 1e-9)

        # 5) update
        TOGW_guess = W0_new
        it += 1

    converged = (delta <= err)
    return TOGW_guess, converged, it, np.array(W0_history)
# Fixed parameters for weight estimation
L_D_max = 9
R = 1000           # nmi, from rfpno 
E = 30 / 60         # min --> hr
c = 0.52            # lb/(lbf hr)
V = 251 * 1.94384   # m/s --> knots

S_ht = 136.8093
S_vt = 70.3202
S_wet_fuselage = 288 #all ft^2
num_engines = 1  # Example number of engines


#region final TOGW
#these values are used as historical reference to give an estimate for the TOGW:
S_wing_ref_F18EF = 500 #ft^2
T0_ref_F18EF = 44000 #this is thrust value for both engines for the F-18E/F, since our num_engines is 1 for our design, to stay consistent

TOGW_guess = 50000  # Initial guess for Takeoff Gross Weight in pounds
final_TOGW, converged, iterations, W0_history = inner_loop_weight(
    TOGW_guess,
    S_wing_ref_F18EF, S_ht, S_vt, S_wet_fuselage,
    num_engines, W_crew, W_payload, T0_ref_F18EF
)

# ploy the convergence history
plt.figure(figsize=(10,6))
plt.plot(W0_history, marker='o')
plt.title('Convergence of TOGW Estimate')
plt.xlabel('Iteration')
plt.ylabel('Estimated TOGW (lb)')
plt.grid()
plt.show()
print("Final estimated TOGW:", final_TOGW, "lb")

#region outer loop def
def outer_loop_thrust_for_one_constraint(
    S_wing_grid,
    TOGW_guess_init,
    T_total_guess_init,      # total thrust guess (all engines), lbf
    num_engines,
    S_ht, S_vt, S_wet_fuselage,
    W_crew, W_payload,
    coef_1_cruise_constraint, coef_2_cruise_constraint,
    tol_T_rel=1e-3,          
    max_iter_T=100,
    relax=1.0                # optional damping: 0.3~1.0 (use <1 if oscillation)
):
    
    T_total_converged = []
    W0_converged = []
    iter_counts = []
    T_total_history_allS = []  # list of arrays (one per S)

    for S_wing in S_wing_grid:

        # Initialize outer loop for this S
        T_total = T_total_guess_init
        T_hist = []

        for k in range(max_iter_T):
            # Convert total thrust to per-engine thrust for the weight model
            T_0 = T_total / num_engines

            # Inner loop: converge weight for (S, T_0)
            W0, wconv, it_w, W0_hist = inner_loop_weight(
                TOGW_guess_init,
                S_wing, S_ht, S_vt, S_wet_fuselage,
                num_engines, W_crew, W_payload, T_0
            )

            # Wing loading from converged weight
            WS = W0 / S_wing

            # Constraint equations: compute required T/W from W/S
            # -----------------------------------------
            # For cruise as example:
            TW_req = coef_1_cruise_constraint/WS + coef_2_cruise_constraint*WS
            # For takeoff as example:
            # TW_req = coef_takeoff_constraint*WS

            # # For landing
            # TW_req = coef_landing_constraint

            # # For climb
            # TW_req = coef_1_climb_constraint
            # -----------------------------------------
            
            # Required total thrust
            T_req = TW_req * W0

            # Store history
            T_hist.append(T_total)

            # Check outer convergence
            if abs(T_req - T_total) / max(abs(T_total), 1e-9) < tol_T_rel:
                T_total = T_req
                break

            # Update thrust (optionally relaxed damping)
            T_total = (1 - relax) * T_total + relax * T_req

        # Save results for this S
        T_total_converged.append(T_total)
        W0_converged.append(W0)
        iter_counts.append(k+1)
        T_total_history_allS.append(np.array(T_hist))

    return (np.array(T_total_converged),
            np.array(W0_converged),
            np.array(iter_counts),
            T_total_history_allS,
            W0, wconv, it_w, W0_hist)

#region outer loop exe
# Set grid of wing areas to analyze
S_wing_grid = list(range(100, 900, 2))  # Example range of wing areas to analyze

TOGW_guess_init = 500000  # Initial guess for Takeoff Gross Weight in pounds
T_total_guess_init = 15000 * num_engines  # Initial guess for total thrust in pounds-force

T_total_curve, W0_curve, n_iter_T, T_hist_allS, W0_final, wconv_final, it_w_final, W0_hist_final = outer_loop_thrust_for_one_constraint(
    S_wing_grid=S_wing_grid,
    TOGW_guess_init=TOGW_guess_init,
    T_total_guess_init=T_total_guess_init,
    num_engines=num_engines,
    S_ht=S_ht, S_vt=S_vt, S_wet_fuselage=S_wet_fuselage,
    W_crew=W_crew, W_payload=W_payload,
    coef_1_cruise_constraint=coef_1_cruise_constraint,
    coef_2_cruise_constraint=coef_2_cruise_constraint,
    tol_T_rel=1e-6,
    max_iter_T=200,
    relax=1
)
# Plot the resulting T vs S curve from the outer loop convergence
T_actual_F18 = 44000
S_actual_F18 = 400
print(f'Actual T for 777: {T_actual_F18} lbf, Actual S for 777: {S_actual_F18} ft^2')

plt.figure(figsize=(16,9))
plt.title('Converged T vs S for Cruise Constraint')
plt.xlabel("Wing Area S (ft^2)")
plt.ylabel("Total Thrust T (lbf)")
plt.plot(S_actual_F18, T_actual_F18, label='Actual 777', marker='x', markersize=10, color='red')
plt.plot(S_wing_grid, T_total_curve, label='Converged T for Cruise Constraint')
plt.legend(loc='best')
plt.grid()
plt.show()
