import numpy as np
import matplotlib.pyplot as plt
import math


#region setup
AR = 3.5
s_ref = 573
g = 32.174

# Drag polar inputs
S_wet = 2044
c_f = 0.0026

def calculate_zero_lift_drag_coefficient(c_f, S_wet, s_ref):
    return c_f * (S_wet / s_ref)


C_D_0 = 0.01755
print("Zero-lift drag coefficient C_D_0:", C_D_0)

def calculate_induced_drag_coefficient(AR, e):
    return 1/(np.pi*AR*e)

# Config oswald and CL (kept for structure consistency)
e_clean   = 0.85
e_takeoff = 0.75
e_landing = 0.7
CLmax_L = 2.0
CLmax_C = 1.5
CLmax_T = 1.7
k_takeoff = 1/(np.pi * e_takeoff * AR) #drag polar constant, see 07-PreliminarySizing_Part3.pdf pg15 in canvas files
k_cruise = 1/(np.pi * e_clean * AR) #drag polar constant, see 07-PreliminarySizing_Part3.pdf pg15 in canvas files

#region cruise coef M2.0

rho_30k = 8.91E-4 #slugs/ft^3, atmospheric density at 30k ft
a   = 996 #996 ft/s is speed of sound at 30kft from NASA standard atmosphere tables
M   = 2.0 #from rfp
V_cruise = M * a              # ft/s

C_D_0_cruise = C_D_0
e_cruise     = e_clean

def calculate_cruise_constraint_coefficients(rho, V, C_D_0, AR, e):
    q = 0.5 * rho * V**2
    coef_1 = q * C_D_0
    coef_2 = 1/(np.pi * AR * e * q)
    return coef_1, coef_2

coef_1_cruise_constraint, coef_2_cruise_constraint = calculate_cruise_constraint_coefficients(
    rho_30k, V_cruise, C_D_0_cruise, AR, e_cruise
)

def TW_from_cruise_at_WS(WS):
    """Cruise constraint: TW = coef1/WS + coef2*WS"""
    WS = np.maximum(WS, 1e-8)
    return (coef_1_cruise_constraint / WS) + (coef_2_cruise_constraint * WS)
# ============================================================


#region stall coef

rho_SL = 23.77e-4  # slugs/ft^3 (sea level)

def WS_stall_takeoff(rho_takeoff, Vstall_takeoff, CLmax_takeoff):
    """WS_stall_takeoff = 0.5*rho_to*Vstall_to^2*CLmax_to"""
    return 0.5 * rho_takeoff * (Vstall_takeoff**2) * CLmax_takeoff

def WS_stall_landing(rho_landing, Vstall_landing, CLmax_landing):
    """WS_stall_landing = 0.5*rho_ld*Vstall_ld^2*CLmax_ld"""
    return 0.5 * rho_landing * (Vstall_landing**2) * CLmax_landing

# --- Takeoff stall values ---
Vstall_T = 205 #ft/s (120 KIAS), stall speed for takeoff (based on F/A-18E/F)
CLmax_takeoff  = CLmax_T
WS_takeoff_stall_val = WS_stall_takeoff(rho_SL, Vstall_T, CLmax_takeoff)
TW_req_takeoff_stall = TW_from_cruise_at_WS(WS_takeoff_stall_val)

print(f"[TAKEOFF STALL] WS_stall = {WS_takeoff_stall_val:.2f} lb/ft^2")
print(f"[TAKEOFF STALL] TW_req (cruise @ WS_stall) = {TW_req_takeoff_stall:.4f}")

# --- Landing stall values ---
Vstall_landing = 220.0
CLmax_landing  = 2.2
WS_landing_stall_val = WS_stall_landing(rho_SL, Vstall_landing, CLmax_landing)
TW_req_landing_stall = TW_from_cruise_at_WS(WS_landing_stall_val)

print(f"[LANDING STALL] WS_stall = {WS_landing_stall_val:.2f} lb/ft^2")
print(f"[LANDING STALL] TW_req (cruise @ WS_stall) = {TW_req_landing_stall:.4f}")
# ============================================================


#region climb coef
k_s = 3.4
CLmax_climb = CLmax_T
G = 0.220



def calculate_climb_constraint_coefficient():
    return (k_s**2 * C_D_0)/(CLmax_climb) + k_takeoff * (CLmax_climb)/(k_s**2) + G

coef_1_climb_constraint = calculate_climb_constraint_coefficient()

print("[CLIMB] TW_req =", coef_1_climb_constraint)

#region takeoff (cat) coef

VWOD = 51 #ft/s (30 kts) "Wind Over Deck" airspeed, or wind speed + carrier cruise velocity
VCAT = 200 #ft/s (120 kts) airspeed generated by forward throw of CATapult
Vlaunch = VWOD + VCAT
WS_takeoff_cat_val = WS_stall_takeoff(rho_SL, Vlaunch, CLmax_T)
TW_req_takeoff_cat = TW_from_cruise_at_WS(WS_takeoff_cat_val) 
def calculate_takeoff_constraint_coefficient(rho, Vwod, Vcat, CLMT):
    coef_takeoff = (0.5 * rho * (Vwod + Vcat)**2 * CLMT)/1.21
    return coef_takeoff
WScoef_takeoff_cat = calculate_takeoff_constraint_coefficient(rho_SL, VWOD, VCAT, CLmax_T) #wing loading constraint for clearing carrier runway on takeoff
coef_takeoff_cat = TW_from_cruise_at_WS(WScoef_takeoff_cat)

#region ceiling coef



ceilingTW = 2 * np.sqrt(k_cruise * C_D_0)




#region 7g turn
# ===================== 6) 7g turn  
# 
# 0_target = 55000.0        # fixed combat/TO weight (lbf)
C_D0_7g = 0.01755          # keep exactly as you provided
e_7g = 0.8
AR_7g = 3.5
k_7g = 1.0 / (math.pi * e_7g * AR_7g)

rho_20k = 12.66e-4         # slugs/ft^3
V_BTR = 500             # ft/s
n_turn = 7.0               # n_tar

q_7g = 0.5 * rho_20k * V_BTR**2
W0_target = 60000.0        # fixed combat/TO weight (lbf)
def TW_7g_from_WS(WS):
    """7g sustained turn constraint: TW = (q*Cd0)/WS + (k*n^2/q)*WS"""
    WS = np.maximum(WS, 1e-9)
    
    return (q_7g * C_D0_7g) / WS + (k_7g * (n_turn**2) / q_7g) * WS

#region (weight for 7g)
def inner_loop_weight_7g(W_guess, tol_W=1e-8, max_iter_W=100, relax_W=0.35):
    """
    Inner loop for diagram-consistent 7g:
    converges W -> W0_target (fixed).
    """
    W = float(max(W_guess, 1.0))
    hist = []
    for it in range(max_iter_W):
        W_new = (1 - relax_W) * W + relax_W * W0_target
        hist.append(W_new)
        rel = abs(W_new - W) / max(abs(W_new), 1e-9)
        W = W_new
        if rel < tol_W:
            return W, True, it+1, np.array(hist)
    return W, False, max_iter_W, np.array(hist)



#===============================================================================================================
#===============================================================================================================
#===============================================================================================================
#                                ._                             
#                               |* ;                            
#             `*-.              |"":                            
#              \  \             |""                             
#               .  \            |   :                           
#               `   \           |                               
#                \   \          |    ;               +.         
#                 .   \         |                   *._`-.      
#                 `    \        |     :          .-*'  `. `.    
#                 _\    \.__..--**--...L_   _.-*'      .'`*'    
#                /  `*-._\   -.       .-*"*+._       .'         
#               :        ``*-._*.     \      _J.   .'           
#           .-*'`*-.       ;     `.    \    /   `.'             
#       .-*'  _.-*'.     .-'       `-.  `-.:   _.'`-.           
#    +*' _.-*'      `..-'             `*-. `**'      `-.        
#     `*'          .-'      ._            `*-._         `.      
#               .-'         `.`-.____..+-**""'         .*"`.    
#          ._.-'          _.-*'''''-;._               /     `.  
#       .-'  `.      _.-*' `*-.__.-*   `"**--..__    :        `.
# .'..-'       \_.-*'                            `"**--..___.-*'
# `. `.    _.-*'                                                
#   `. `:*'                                                     
#     `. `.                                                     
#       `*
#===============================================================================================================
#===============================================================================================================
#===============================================================================================================



#region weight model

num_pilot = 1
avg_wt_person = 200
W_payload = 2500

W_crew = num_pilot * avg_wt_person
W_payload = W_crew + W_payload

L_D_max = 9
R = 1000
E = 30 / 60
c = 0.52
V_knots = 291 * 1.94

S_ht = 0
S_vt = 74
S_wet_fuselage = 288
num_engines = 1

def calculate_engine_weight(T_0):
    W_eng_dry = 0.521 * T_0**0.9
    W_eng_oil = 0.082 * T_0**0.65
    W_eng_rev = 0.034 * T_0
    W_eng_control = 0.26 * T_0**0.5
    W_eng_start = 9.33 * (W_eng_dry/1000) ** 1.078
    return W_eng_dry + W_eng_oil + W_eng_rev + W_eng_control + W_eng_start

def calculate_empty_weight(S_wing, S_ht, S_vt, S_wet_fuselage, TOGW, T_0 , num_engines):
    # i changed these from the transport to the fighter values, using raymer (they matched the 777 before) -charlie
    W_wing = S_wing * 9 
    W_ht = S_ht * 4
    W_vt = S_vt * 5.3
    W_fuselage = S_wet_fuselage * 4.8
    W_landing_gear = 0.045 * TOGW
    Engine_weight = calculate_engine_weight(T_0)
    W_engines = Engine_weight * num_engines * 1.3
    W_all_else = 0.17 * TOGW

    # Fighter scaling factor 
    fighter_scale = 3.5
    W_empty = fighter_scale * (W_wing + W_ht + W_vt + W_fuselage) + W_landing_gear + W_engines + W_all_else
    return W_empty

def calculate_weight_fraction(L_D_max, R, E, c, V):
    L_D = 0.94 * L_D_max
    W3_W2 = np.exp((-R*c) / (V*L_D))  # cruise
    W4_W3 = np.exp((-E*c) / (L_D))    # loiter

    # segment fractions
    W1_W0 = 0.990
    W2_W1 = 0.980
    W5_W4 = 0.995

    W5_W0 = W5_W4 * W4_W3 * W3_W2 * W2_W1 * W1_W0
    return (1 - W5_W0) * 1.06

def inner_loop_weight(
    TOGW_guess,
    S_wing, S_ht, S_vt, S_wet_fuselage,
    num_engines, w_crew, w_payload, T_0,
    err=1e-6,
    max_iter=200
):
    delta = np.inf
    it = 0

    while delta > err and it < max_iter:
        Wf_W0 = calculate_weight_fraction(L_D_max, R, E, c, V_knots)
        W_fuel = Wf_W0 * TOGW_guess

        W_empty = calculate_empty_weight(
            S_wing, S_ht, S_vt, S_wet_fuselage,
            TOGW_guess, T_0, num_engines
        )

        W0_new = W_empty + w_crew + w_payload + W_fuel
        delta = abs(W0_new - TOGW_guess) / max(abs(W0_new), 1e-9)
        TOGW_guess = W0_new
        it += 1

    return TOGW_guess, (delta <= err), it



#===============================================================================================================
#===============================================================================================================
#===============================================================================================================
#                                ._                             
#                               |* ;                            
#             `*-.              |"":                            
#              \  \             |""                             
#               .  \            |   :                           
#               `   \           |                               
#                \   \          |    ;               +.         
#                 .   \         |                   *._`-.      
#                 `    \        |     :          .-*'  `. `.    
#                 _\    \.__..--**--...L_   _.-*'      .'`*'    
#                /  `*-._\   -.       .-*"*+._       .'         
#               :        ``*-._*.     \      _J.   .'           
#           .-*'`*-.       ;     `.    \    /   `.'             
#       .-*'  _.-*'.     .-'       `-.  `-.:   _.'`-.           
#    +*' _.-*'      `..-'             `*-. `**'      `-.        
#     `*'          .-'      ._            `*-._         `.      
#               .-'         `.`-.____..+-**""'         .*"`.    
#          ._.-'          _.-*'''''-;._               /     `.  
#       .-'  `.      _.-*' `*-.__.-*   `"**--..__    :        `.
# .'..-'       \_.-*'                            `"**--..___.-*'
# `. `.    _.-*'                                                
#   `. `:*'                                                     
#     `. `.                                                     
#       `*
#===============================================================================================================
#===============================================================================================================
#===============================================================================================================



# region outer stall
def outer_loop_thrust_stall(
    S_wing_grid,
    WS_stall_target,
    TW_req_stall_target,
    T_total_guess_init,
    num_engines,
    S_ht, S_vt, S_wet_fuselage,
    W_crew, W_payload,
    tol_T_rel=1e-6,
    max_iter_T=200,
    relax=1.0
):
    """
    Stall outer loop:
    - Sets local TOGW guess from the stall wing-loading: TOGW_guess_local = WS_stall * S
    - Uses TW_req_stall_target (computed from cruise @ WS_stall)
    - Converges total thrust: T_req = TW_req * W0
    """
    T_total_converged = []
    W0_converged = []
    iter_counts = []

    for S_wing in S_wing_grid:
        T_total = T_total_guess_init
        TOGW_guess = WS_stall_target * S_wing

        for k in range(max_iter_T):
            # Single engine -> per-engine thrust = total thrust
            T_0 = T_total / max(num_engines, 1)

            W0, wconv, it_w = inner_loop_weight(
                TOGW_guess,
                S_wing, S_ht, S_vt, S_wet_fuselage,
                num_engines, W_crew, W_payload, T_0
            )

            ws = W0 / S_wing

            # ----------------------------- ADD YOUR CONSTRAINT LINE HERE ------------------------------
            # For STALL: use TW target (different for TO vs LD)
            TW_req = TW_req_stall_target
            # ------------------------------------------------------------------------------------------

            T_req = TW_req * W0

            if abs(T_req - T_total) / max(abs(T_total), 1e-9) < tol_T_rel:
                T_total = T_req
                break

            T_total = (1 - relax) * T_total + relax * T_req

        T_total_converged.append(T_total)
        W0_converged.append(W0)
        iter_counts.append(k+1)

    return np.array(T_total_converged), np.array(W0_converged), np.array(iter_counts)

#region outer cat takeoff
def outer_loop_thrust_cat(
    S_wing_grid,
    WS_cat_target,
    TW_req_cat_target,
    T_total_guess_init,
    num_engines,
    S_ht, S_vt, S_wet_fuselage,
    W_crew, W_payload,
    tol_T_rel=1e-6,
    max_iter_T=200,
    relax=1.0
):
    """
    Catapult takeoff outer loop:
    - Sets local TOGW guess from the catapult wing-loading: TOGW_guess_local = WS_cat * S
    - Uses TW_req_cat_target (computed from cruise @ WS_cat)
    - Converges total thrust: T_req = TW_req * W0
    """
    T_total_converged = []
    W0_converged = []
    iter_counts = []

    for S_wing in S_wing_grid:
        T_total = T_total_guess_init
        TOGW_guess = WS_cat_target * S_wing

        for k in range(max_iter_T):
            # Single engine -> per-engine thrust = total thrust
            T_0 = T_total / max(num_engines, 1)

            W0, wconv, it_w = inner_loop_weight(
                TOGW_guess,
                S_wing, S_ht, S_vt, S_wet_fuselage,
                num_engines, W_crew, W_payload, T_0
            )

            ws = W0 / S_wing

            # ----------------------------- ADD YOUR CONSTRAINT LINE HERE ------------------------------
            # For cat: use TW target (different for TO vs LD)
            TW_req = coef_takeoff_cat
            # ------------------------------------------------------------------------------------------

            T_req = TW_req * W0

            if abs(T_req - T_total) / max(abs(T_total), 1e-9) < tol_T_rel:
                T_total = T_req
                break

            T_total = (1 - relax) * T_total + relax * T_req

        T_total_converged.append(T_total)
        W0_converged.append(W0)
        iter_counts.append(k+1)

    return np.array(T_total_converged), np.array(W0_converged), np.array(iter_counts)


# region outer climb
def outer_loop_thrust_climb(
    S_wing_grid,
    TOGW_guess_init,
    T_total_guess_init,
    num_engines,
    S_ht, S_vt, S_wet_fuselage,
    W_crew, W_payload,
    coef_1_climb_constraint,
    tol_T_rel=1e-6,
    max_iter_T=200,
    relax=1.0
):
    """
    Climb outer loop:
    - Uses constant TW_req = coef_1_climb_constraint
    - Converges T so that T = TW_req * W0
    """
    T_total_converged = []
    W0_converged = []
    iter_counts = []

    for S_wing in S_wing_grid:
        T_total = T_total_guess_init

        for k in range(max_iter_T):
            T_0 = T_total 

            W0, wconv, it_w = inner_loop_weight(
                TOGW_guess_init,
                S_wing, S_ht, S_vt, S_wet_fuselage,
                num_engines, W_crew, W_payload, T_0
            )

            # ----------------------------- ADD YOUR CONSTRAINT LINE HERE ------------------------------
            TW_req = coef_1_climb_constraint
            # ------------------------------------------------------------------------------------------

            T_req = TW_req * W0

            if abs(T_req - T_total) / max(abs(T_total), 1e-9) < tol_T_rel:
                T_total = T_req
                break

            T_total = (1 - relax) * T_total + relax * T_req

        T_total_converged.append(T_total)
        W0_converged.append(W0)
        iter_counts.append(k+1)

    return np.array(T_total_converged), np.array(W0_converged), np.array(iter_counts)


# region outer ceiling
def outer_loop_thrust_ceiling(
    S_wing_grid,
    TOGW_guess_init,
    T_total_guess_init,
    num_engines,
    S_ht, S_vt, S_wet_fuselage,
    W_crew, W_payload,
    TW_ceiling,
    tol_T_rel=1e-6,
    max_iter_T=200,
    relax=1.0
):
    """
    Climb outer loop:
    - Uses constant TW_req = coef_1_climb_constraint
    - Converges T so that T = TW_req * W0
    """
    T_total_converged = []
    W0_converged = []
    iter_counts = []

    for S_wing in S_wing_grid:
        T_total = T_total_guess_init

        for k in range(max_iter_T):
            T_0 = T_total 

            W0, wconv, it_w = inner_loop_weight(
                TOGW_guess_init,
                S_wing, S_ht, S_vt, S_wet_fuselage,
                num_engines, W_crew, W_payload, T_0
            )

            # ----------------------------- ADD YOUR CONSTRAINT LINE HERE ------------------------------
            TW_req = TW_ceiling
            # ------------------------------------------------------------------------------------------

            T_req = TW_req * W0

            if abs(T_req - T_total) / max(abs(T_total), 1e-9) < tol_T_rel:
                T_total = T_req
                break

            T_total = (1 - relax) * T_total + relax * T_req

        T_total_converged.append(T_total)
        W0_converged.append(W0)
        iter_counts.append(k+1)

    return np.array(T_total_converged), np.array(W0_converged), np.array(iter_counts)

# ============================================================


# region outer cruise M2.0
def outer_loop_thrust_for_onepointsixmach_constraint(
    S_wing_grid,
    TOGW_guess_init,
    T_total_guess_init,
    num_engines,
    S_ht, S_vt, S_wet_fuselage,
    W_crew, W_payload,
    coef_1_cruise_constraint, coef_2_cruise_constraint,
    tol_T_rel=1e-6,
    max_iter_T=100,
    relax=1.0
):

    T_total_converged = []
    W0_converged = []
    iter_counts = []
    T_total_history_allS = []

    for S_wing in S_wing_grid:

        T_total = T_total_guess_init
        T_hist = []

        for k in range(max_iter_T):

            T_0 = T_total / num_engines

            W0, wconv, it_w= inner_loop_weight(
                TOGW_guess_init,
                S_wing, S_ht, S_vt, S_wet_fuselage,
                num_engines, W_crew, W_payload, T_0
            )

            WS = W0 / S_wing

            W_to = W0

            T_to = 0.6 * W_to
            T_cr = 0.5 * T_to

            
            W_cr = 0.9021 * W_to
            WS_new = (W_cr / W_to) * WS

            TW_req = (W_cr / W_to) / (T_cr / T_to) * (coef_1_cruise_constraint / WS_new + coef_2_cruise_constraint * WS_new)
            T_req = TW_req * W0

            T_hist.append(T_total)

            if abs(T_req - T_total) / max(abs(T_total), 1e-9) < tol_T_rel:
                T_total = T_req
                break

            T_total = (1 - relax) * T_total + relax * T_req

        T_total_converged.append(T_total)
        W0_converged.append(W0)
        iter_counts.append(k + 1)
        T_total_history_allS.append(np.array(T_hist))

    return (
        np.array(T_total_converged),
        np.array(W0_converged),
        np.array(iter_counts),
        T_total_history_allS,
    )



#region outer manuv 7g
def outer_loop_thrust_for_S_7g(S, T_guess=40000.0, W_guess=55000.0,
                              tol_T=1e-6, max_iter_T=200, relax_T=0.35,
                              tol_W=1e-8, max_iter_W=100):
    """
    Outer loop for diagram-consistent 7g:
      - inner loop: W -> W0_target
      - outer loop: T -> TW(W/S)*W
    """
    T = float(max(T_guess, 1.0))
    T_hist = []

    # inner loop (weight)
    W, wconv, itW, W_hist = inner_loop_weight_7g(W_guess, tol_W=tol_W, max_iter_W=max_iter_W)

    # outer loop (thrust)
    for itT in range(max_iter_T):
        WS = W / float(S)
        TW_req = float(TW_7g_from_WS(WS))
        T_req = TW_req * 6000

        T_hist.append(T)
        relT = abs(T_req - T) / max(abs(T), 1e-9)
        if relT < tol_T:
            return T_req, W, True, itT+1, np.array(T_hist), W_hist

        T = (1 - relax_T) * T + relax_T * T_req

    return T, W, False, max_iter_T, np.array(T_hist), W_hist
# ============================================================



#===============================================================================================================
#===============================================================================================================
#===============================================================================================================
#                                ._                             
#                               |* ;                            
#             `*-.              |"":                            
#              \  \             |""                             
#               .  \            |   :                           
#               `   \           |                               
#                \   \          |    ;               +.         
#                 .   \         |                   *._`-.      
#                 `    \        |     :          .-*'  `. `.    
#                 _\    \.__..--**--...L_   _.-*'      .'`*'    
#                /  `*-._\   -.       .-*"*+._       .'         
#               :        ``*-._*.     \      _J.   .'           
#           .-*'`*-.       ;     `.    \    /   `.'             
#       .-*'  _.-*'.     .-'       `-.  `-.:   _.'`-.           
#    +*' _.-*'      `..-'             `*-. `**'      `-.        
#     `*'          .-'      ._            `*-._         `.      
#               .-'         `.`-.____..+-**""'         .*"`.    
#          ._.-'          _.-*'''''-;._               /     `.  
#       .-'  `.      _.-*' `*-.__.-*   `"**--..__    :        `.
# .'..-'       \_.-*'                            `"**--..___.-*'
# `. `.    _.-*'                                                
#   `. `:*'                                                     
#     `. `.                                                     
#       `*
#===============================================================================================================
#===============================================================================================================
#===============================================================================================================



#region plot stall takeoff

# --- S grid for your fighter-ish sizing ---
S_wing_grid = np.linspace(300, 600, 50)

TOGW_guess_init = 55000
T_total_guess_init = 45000

# 7.1 Takeoff stall curve
T_takeoff_stall, W_takeoff_stall, it_takeoff = outer_loop_thrust_stall(
    S_wing_grid=S_wing_grid,
    WS_stall_target=WS_takeoff_stall_val,
    TW_req_stall_target=TW_req_takeoff_stall,
    T_total_guess_init=T_total_guess_init,
    num_engines=num_engines,
    S_ht=S_ht, S_vt=S_vt, S_wet_fuselage=S_wet_fuselage,
    W_crew=W_crew, W_payload=W_payload
)

plt.figure(figsize=(12,7))
plt.plot(S_wing_grid, T_takeoff_stall, marker='o', linewidth=2, label="Takeoff stall")
plt.xlabel("Wing Area S (ft²)")
plt.ylabel("Total Thrust T (lbf)")
plt.title("Converged T vs S — Takeoff Stall Constraint")
plt.grid(True)
plt.legend()
plt.show()

#region plot cat takeoff

# --- S grid for your fighter-ish sizing ---
S_wing_grid = np.linspace(300, 600, 50)

TOGW_guess_init = 55000
T_total_guess_init = 45000

# 7.1 Takeoff cat curve
T_takeoff_cat, W_takeoff_cat, it_takeoff = outer_loop_thrust_cat(
    S_wing_grid=S_wing_grid,
    WS_cat_target=WS_takeoff_cat_val,
    TW_req_cat_target=TW_req_takeoff_cat,
    T_total_guess_init=T_total_guess_init,
    num_engines=num_engines,
    S_ht=S_ht, S_vt=S_vt, S_wet_fuselage=S_wet_fuselage,
    W_crew=W_crew, W_payload=W_payload
)

plt.figure(figsize=(12,7))
plt.plot(S_wing_grid, T_takeoff_cat, marker='o', linewidth=2, label="Catapult Takeoff")
plt.xlabel("Wing Area S (ft²)")
plt.ylabel("Total Thrust T (lbf)")
plt.title("Converged T vs S — Takeoff Catapult Constraint")
plt.grid(True)
plt.legend()
plt.show()

# region plot stall landing
T_landing_stall, W_landing_stall, it_landing = outer_loop_thrust_stall(
    S_wing_grid=S_wing_grid,
    WS_stall_target=WS_landing_stall_val,
    TW_req_stall_target=TW_req_landing_stall,
    T_total_guess_init=T_total_guess_init,
    num_engines=num_engines,
    S_ht=S_ht, S_vt=S_vt, S_wet_fuselage=S_wet_fuselage,
    W_crew=W_crew, W_payload=W_payload
)

plt.figure(figsize=(12,7))
plt.plot(S_wing_grid, T_landing_stall, marker='o', linewidth=2, label="Landing stall")
plt.xlabel("Wing Area S (ft²)")
plt.ylabel("Total Thrust T (lbf)")
plt.title("Converged T vs S — Landing Stall Constraint")
plt.grid(True)
plt.legend()
plt.show()

# region plot climb
T_climb, W_climb, it_climb = outer_loop_thrust_climb(
    S_wing_grid=S_wing_grid,
    TOGW_guess_init=TOGW_guess_init,
    T_total_guess_init=T_total_guess_init,
    num_engines=num_engines,
    S_ht=S_ht, S_vt=S_vt, S_wet_fuselage=S_wet_fuselage,
    W_crew=W_crew, W_payload=W_payload,
    coef_1_climb_constraint=coef_1_climb_constraint
)

plt.figure(figsize=(12,7))
plt.plot(S_wing_grid, T_climb, marker='o', linewidth=2, label="Climb")
plt.xlabel("Wing Area S (ft²)")
plt.ylabel("Total Thrust T (lbf)")
plt.title("Converged T vs S — Climb Constraint")
plt.grid(True)
plt.legend()
plt.show()

# region plot ceiling
T_ceiling, W_ceiling, it_ceiling = outer_loop_thrust_ceiling(
    S_wing_grid=S_wing_grid,
    TOGW_guess_init=TOGW_guess_init,
    T_total_guess_init=T_total_guess_init,
    num_engines=num_engines,
    S_ht=S_ht, S_vt=S_vt, S_wet_fuselage=S_wet_fuselage,
    W_crew=W_crew, W_payload=W_payload,
    TW_ceiling=ceilingTW
)

plt.figure(figsize=(12,7))
plt.plot(S_wing_grid, T_ceiling, marker='o', linewidth=2, label="Climb")
plt.xlabel("Wing Area S (ft²)")
plt.ylabel("Total Thrust T (lbf)")
plt.title("Converged T vs S — Ceiling Constraint")
plt.grid(True)
plt.legend()
plt.show()

# region manuv 7g
S_grid_7g = np.linspace(300, 600, 50)
T_guess_7g = 40000
W_guess_7g = 50000
tol_T_7g = 1e-6
max_iter_T_7g = 200
relax_T_7g = 0.35
tol_W_7g = 1e-8
max_iter_W_7g = 100

T_curve_7g = []
W_curve_7g = []
conv_flags_7g = []
outer_iters_7g = []

for S in S_grid_7g:
    T_sol, W_sol, conv, itT, Thist, Whist = outer_loop_thrust_for_S_7g(
        S,
        T_guess=T_guess_7g,
        W_guess=W_guess_7g,
        tol_T=tol_T_7g,
        max_iter_T=max_iter_T_7g,
        relax_T=relax_T_7g,
        tol_W=tol_W_7g,
        max_iter_W=max_iter_W_7g
    )
    T_curve_7g.append(T_sol)
    W_curve_7g.append(W_sol)
    conv_flags_7g.append(conv)
    outer_iters_7g.append(itT)

T_curve_7g = np.array(T_curve_7g)
W_curve_7g = np.array(W_curve_7g)

plt.figure(figsize=(12,7))
plt.plot(S_grid_7g, T_curve_7g, marker='o', linewidth=2, label="7g Sustained Turn @20kft")
plt.xlabel("Wing Area S (ft²)")
plt.ylabel("Total Thrust T (lbf)")
plt.title("Converged T vs S — 7g Sustained Turn Constraint")
plt.grid(True)
plt.legend()
plt.show()

# convergence plots for the 7g demo point (middle of the S grid)
S_demo = 375
T_sol, W_sol, conv, itT, Thist, Whist = outer_loop_thrust_for_S_7g(
    S_demo,
    T_guess=T_guess_7g,
    W_guess=W_guess_7g,
    tol_T=tol_T_7g,
    max_iter_T=max_iter_T_7g,
    relax_T=relax_T_7g,
    tol_W=tol_W_7g,
    max_iter_W=max_iter_W_7g
)

plt.figure(figsize=(12,6))
plt.plot(Whist, marker='o')
plt.xlabel("Inner iteration k")
plt.ylabel("W estimate (lb)")
plt.title(f"Inner loop convergence (W) — S = {S_demo:.0f} ft²")
plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))
plt.plot(Thist, marker='o')
plt.xlabel("Outer iteration k")
plt.ylabel("T guess (lbf)")
plt.title(f"Outer loop convergence (T) — 7g turn at S = {S_demo:.0f} ft²")
plt.grid(True)
plt.show()

print("=== 7g Iteration settings (report these) ===")
print(f"S grid: {S_grid_7g[0]:.0f} to {S_grid_7g[-1]:.0f} ft^2, N = {len(S_grid_7g)}")
print("Constraint: Sustained Turn 7g @ 20kft (diagram-consistent)")
print(f"W0_target = {W0_target:.0f} lb")
print(f"rho_20k = {rho_20k:.3e} slugs/ft^3, V_BTR = {V_BTR:.1f} ft/s, n = {n_turn:.1f}")
print(f"CD0 = {C_D0_7g:.5f}, AR = {AR_7g:.2f}, e = {e_7g:.2f}, k = {k_7g:.5f}")
print(f"Outer loop: T_guess={T_guess_7g:.0f}, tol_T={tol_T_7g:.1e}, max_iter_T={max_iter_T_7g}, relax_T={relax_T_7g}")
print(f"Inner loop: W_guess={W_guess_7g:.0f}, tol_W={tol_W_7g:.1e}, max_iter_W={max_iter_W_7g}")
print()
print("=== 7g Demo point ===")
print(f"S_demo = {S_demo:.0f} ft^2 | converged={conv} | outer iters={itT} | W={W_sol:,.1f} lb | T={T_sol:,.1f} lbf")
print(f"Converged across S grid: {sum(conv_flags_7g)}/{len(conv_flags_7g)} points")


# region plot cruise M2.0
TOGW_guess = 55000
S_wing_grid = np.linspace(300, 600, 50)
#values at 30000 ft of altitude above the sea level.
rho = 8.9e-4      # slugs/ft^3 (ISA @ 30,000 ft)
a   = 995           # ft/s (ISA @ 30,000 ft)
M   = 1.6
V = M * a   
e_cruise = e_clean
C_D_0 = 0.01760
C_D_0_cruise = C_D_0
def calculate_cruise_constraint_coefficients(rho, V, C_D_0, AR, e):
    q = 0.5 * rho * V**2   
    coef_1 = q * C_D_0
    coef_2 = 1/(np.pi * AR * e * q)
    return coef_1, coef_2
coef_1_cruise_constraint, coef_2_cruise_constraint = calculate_cruise_constraint_coefficients(rho, V, C_D_0_cruise, AR, e_cruise)
T_total_guess_init = 60000

T_cruise_M2, W0_curve, iters, T_histories = outer_loop_thrust_for_onepointsixmach_constraint(
    S_wing_grid,
    TOGW_guess,
    T_total_guess_init,
    num_engines,
    S_ht, S_vt, S_wet_fuselage,
    W_crew, W_payload,
    coef_1_cruise_constraint,
    coef_2_cruise_constraint
)

plt.figure(figsize=(16,9))
plt.title('Converged T vs S for Cruise Constraint')
plt.xlabel("Wing Area S (ft^2)")
plt.ylabel("Total Thrust T (lbf)")

plt.plot(S_wing_grid, T_cruise_M2, label='Converged T for Cruise Constraint', marker='o')
plt.legend(loc='best')
plt.grid()
plt.show()

# region plot final
plt.figure(figsize=(16,9))
plt.title("Converged T vs S — Combined Constraints")
plt.xlabel("Wing Area S (ft²)")
plt.ylabel("Total Thrust T (lbf)")
plt.xlim(300, 600)
plt.ylim(0, 50000)

plt.plot(S_wing_grid, T_takeoff_stall, linewidth=2, label="Takeoff stall (V=205, CLmax=1.7)")
plt.plot(S_wing_grid, T_landing_stall, linewidth=2, label="Landing stall (V=220, CLmax=2.2)")
plt.plot(S_wing_grid, T_climb, linewidth=2, label="Climb (constant TW)")
plt.plot(S_grid_7g,  T_curve_7g, linewidth=2, label="7g sustained turn @20kft")
plt.plot(S_wing_grid, T_cruise_M2, linewidth=2, label="2.0 Mach Cruise Constraint @30kft")
plt.plot(S_wing_grid, T_takeoff_cat, linewidth=2, label=f"Catapult Constraint (VWOD={VWOD}, VCAT={VCAT})")
plt.plot(S_wing_grid, T_ceiling, linewidth=2, label=f"Ceiling Constraint")

Selected_T = 35000
Selected_S = 375

F18EF_T = 22000*2
F18EF_S = 500

F35_T = 43000
F35_S = 460

SU27_T = 27600*2
SU27_S = 670

#all lbf, ft^2

plt.plot(Selected_S, Selected_T, label = f'Design Point: S={Selected_S}, T={Selected_T}', marker = '*', color="gold")
plt.plot(F18EF_S, F18EF_T, label = f'F/A-18E/F: S={F18EF_S}, T={F18EF_T}', marker = 'o')
plt.plot(SU27_S, SU27_T, label = f'Su-27: S={SU27_S}, T={SU27_T}', marker = 'o', color="red")
plt.plot(F35_S, F35_T, label = f'F-35C: S={F35_S}, T={F35_T}', marker = 'o')
T_envelope = np.maximum.reduce([
    T_takeoff_stall,
    T_landing_stall,
    T_climb,
    T_cruise_M2,
    T_takeoff_cat,
    T_ceiling
])


T_envelope = np.maximum(T_envelope, T_curve_7g)
plt.fill_between(
    S_wing_grid,
    T_envelope,
    50000,
    color='green',
    alpha=0.2,
    label="Feasible Design Region"
)

plt.legend(loc="best")
plt.show()
# ============================================================================
